[package]
name = "Task_9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]] 
name = "part-1" 
path = "src/part-1.rs" 
bench = true 
