[package]
name = "Task_3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part-2"
path = "./src/part-2.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
